version: '3'
services:
  mysql-innodb-cluster-vm1:
    image: quay.io/redhattelco/intelli-infra-mysql
    container_name: mysql-innodb-cluster-vm1
    restart: always
    volumes:
        - ./data/vm1:/var/lib/postgresql/data
    ports:
      - "3306:3306"
    environment:
      - 'MYSQL_ROOT_PASSWORD=verySecurePa33w0rd'
  mysql-innodb-cluster-vm2:
    image: quay.io/redhattelco/intelli-infra-mysql
    container_name: mysql-innodb-cluster-vm2
    restart: always
    volumes:
        - ./data/vm2:/var/lib/postgresql/data
    ports:
      - "3306:3306"
    environment:
      - 'MYSQL_ROOT_PASSWORD=verySecurePa33w0rd'
  mysql-innodb-cluster-vm3:
    image: quay.io/redhattelco/intelli-infra-mysql
    container_name: mysql-innodb-cluster-vm3
    restart: always
    volumes:
        - ./data/vm3:/var/lib/postgresql/data
    ports:
      - "3306:3306"
    environment:
      - 'MYSQL_ROOT_PASSWORD=verySecurePa33w0rd'    
networks:
  default:
    external:
      name: mysql-cluster-net