version: '3'
services:
  mysql-vm1:
    # image: quay.io/redhattelco/intelli-infra-mysql
    image: mysql/mysql-server:8.0.19
    container_name: mysql-vm1
    hostname: mysql-vm1
    restart: always
    volumes:
        - ./data/mysql-vm1:/var/lib/mysql
        # - ./config/mysql.conf.d:/etc/mysql/conf.d
    # ports:
    #   - "3306:3306"
    environment:
      - 'MYSQL_ROOT_PASSWORD=verySecurePa33w0rd'
  mysql-vm2:
    # image: quay.io/redhattelco/intelli-infra-mysql
    image: mysql/mysql-server:8.0.19
    container_name: mysql-vm2
    hostname: mysql-vm2
    restart: always
    volumes:
        - ./data/mysql-vm2:/var/lib/mysql
    # ports:
    #   - "3307:3306"
    environment:
      - 'MYSQL_ROOT_PASSWORD=verySecurePa33w0rd'
  mysql-vm3:
    # image: quay.io/redhattelco/intelli-infra-mysql
    image: mysql/mysql-server:8.0.19
    container_name: mysql-vm3
    hostname: mysql-vm3
    restart: always
    volumes:
        - ./data/mysql-vm3:/var/lib/mysql
    # ports:
    #   - "3308:3306"
    environment:
      - 'MYSQL_ROOT_PASSWORD=verySecurePa33w0rd'    
networks:
  default:
    external:
      name: mysql-innodb-net